databases:
  - name: Ledger
    databaseName: Ledger
    user: Ledger

services:
  - type: web
    name: Ledger
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Ledger
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false